config/routes.rb
Rails.application.routes.draw do
  resources :players do
    collection do
      post 'search'
    end
  end
  
  resources :partners do
    collection do
      post :search, to: "partners/searches#index"
    end
  end
  resources :articles
  get 'home/index'
  get 'other/index'

  get '/home/turbo_frame_form' => 'home#turbo_frame_form', as: 'turbo_frame_form'
  post '/home/turbo_frame_submit' => 'home#turbo_frame_submit', as: 'turbo_frame_submit'

  post '/other/post_something' => 'other#post_something', as: 'post_something'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = articles
    @query = query
  end

  # GET /articles/1 or /articles/1.json
  def show
    # request.variant
    @article = Article.find(params[:id])
    request.variant = Current.user.admin? ? :admin : :user
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def articles
      if query
        Article.where("title ILIKE ?", "%#{query}%")
      else
        Article.all
      end
    end

    def query
      params[:query]
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.fetch(:article, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # @route GET /turbo_frame_form 
  def turbo_frame_form
  end

  # @route POST /turbo_frame_submit 
  def turbo_frame_submit
    extracted_anynumber = params[:any][:anynumber]
    render :turbo_frame_form, status: :ok, locals: {anynumber: extracted_anynumber, comment: 'turbo_frame_submit ok' }
  end
end

app/controllers/other_controller.rb
class OtherController < ApplicationController

  def post_something
    respond_to do |format|
      format.turbo_stream {  }
    end
  end

end

app/controllers/partners/searches_controller.rb
class Partners::SearchesController < ApplicationController
  def index
    respond_to do |format|
      format.turbo_stream do
        @partners = Partner.where("name LIKE :name", name: "%#{params[:search_term]}%")
  
        render turbo_stream: turbo_stream.replace(
          :partnerListing,
          partial: "partners/listing"
        )
      end
    end
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: %i[ show edit update destroy ]

  # GET /partners or /partners.json
  def index
    @partners = if params[:search_term].present?
      # Since we're using this in two controllers now it might be
      # wise to abstract it out into a Model method
      Partner.where("name LIKE :name", name: "%#{params[:search_term]}%")
    else
      Partner.all
    end
  end

  # GET /partners/1 or /partners/1.json
  def show
  end

  # GET /partners/new
  def new
    @partner = Partner.new
  end

  # GET /partners/1/edit
  def edit
  end

  # POST /partners or /partners.json
  def create
    @partner = Partner.new(partner_params)

    respond_to do |format|
      if @partner.save
        format.html { redirect_to partner_url(@partner), notice: "Partner was successfully created." }
        format.json { render :show, status: :created, location: @partner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /partners/1 or /partners/1.json
  def update
    respond_to do |format|
      if @partner.update(partner_params)
        format.html { redirect_to partner_url(@partner), notice: "Partner was successfully updated." }
        format.json { render :show, status: :ok, location: @partner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1 or /partners/1.json
  def destroy
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to partners_url, notice: "Partner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_partner
      @partner = Partner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def partner_params
      params.require(:partner).permit(:name)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    if params[:query].present?
      @players = Player.where("name LIKE ?", "%#{params[:query]}%")
    else
      @players = Player.all
    end
  
    render turbo_stream: turbo_stream.replace(
      'players',
      partial: 'list',
      locals: {
        players: @players
      }
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/partners/searches_helper.rb
module Partners::SearchesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<%= link_to "New article", new_article_path %>

<%= form_with(
  url: articles_path,
  method: :get,
  data: {
    controller: "submit-form",
    submit_form_target: "form",
  }
) do |f| %>
  <%= f.text_field(
    :query,
    value: @query,
    placeholder: "Search",
    data: {
      action: "input->submit-form#submit",
      disable_with: false
    }
  ) %>
<% end %>

<div id="articles">
  <div class="row">
    <% @articles.each do |article| %>
      <div class="card" style="width: 18rem;margin:2px;">
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= article.description %></p>
          <%= link_to "Show this article", article, class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html+admin.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>
ADMIN
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/articles/show.html+user.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>
USER
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>This is home</h1>
<div><%= link_to "go to other page", other_index_path %></div>

<%= turbo_frame_tag 'anyframe' do %>        
  <div>
    <h2>Home view</h2>
    <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
      <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
      <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
      <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
    <% end %>
  <div>
<% end %>

app/views/home/turbo_frame_form.html.erb
<section>
  <%= turbo_frame_tag 'anyframe' do %>        
    <div>
      <h2>Frame view</h2>
      <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
        <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
        <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
        <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
      <% end %>
    </div>
    <div>
      <h2>Data of the view</h2>
      <pre style="font-size: .7rem;"><%= JSON.pretty_generate(local_assigns) %></pre> 
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/other/index.html.erb
<h1>This is another page</h1>
<div><%= link_to "go to home page", root_path %></div>

<div style="margin-top: 2rem;">
  <%= form_with scope: :any, url: post_something_path do |form| %>
      <%= form.submit 'Post something' %>
  <% end %>
  <turbo-frame id="messages">
    <div>An empty message</div>
  </turbo-frame>
</div>

<div style="margin-top: 2rem;">
  <h2>Stimulus</h2>  
  <div data-controller="hello">
    <input data-hello-target="name" type="text">
    <button data-action="click->hello#greet">
      Greet
    </button>
    <span data-hello-target="output">
    </span>
  </div>
</div>

app/views/other/post_something.turbo_stream.erb
<turbo-stream action="replace" target="messages">
  <template>
    <div id="message_1">This changes the existing message!</div>
  </template>
</turbo-stream>

app/views/partners/_form.html.erb
<%= form_with(model: partner) do |form| %>
  <% if partner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(partner.errors.count, "error") %> prohibited this partner from being saved:</h2>

      <ul>
        <% partner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/partners/_listing.html.erb
<!--app/views/partners/_listing.html.erb-->
<tbody id="partnerListing">
  <% @partners.each do |partner| %>
    <tr>
      <td><%= partner.name %></td>
      <td><%= link_to 'Show', partner %></td>
      <td><%= link_to 'Edit', edit_partner_path(partner) %></td>
      <td><%= link_to 'Destroy', partner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

  <!-- Blank state -->
  <% if @partners.empty? %>
    <tr>
      <td><em>No matching partners</em></td>
    </tr>
  <% end %>
</tbody>

app/views/partners/_partner.html.erb
<div id="<%= dom_id partner %>">
  <p>
    <strong>Name:</strong>
    <%= partner.name %>
  </p>

</div>

app/views/partners/edit.html.erb
<%= turbo_frame_tag "partner" do %>
  <%= render 'form', partner: @partner %>
  
  <%= link_to 'Show', @partner %> |
  <%= link_to 'Back', partners_path, data: { "turbo-frame": "_top" } %>
<% end %>

app/views/partners/index.html.erb
<%= form_with url: search_partners_path, data: { controller: "search" } do |form| %>
 <%= form.text_field 'search_term', placeholder: 'Enter search terms...', data: { "search-target" => "term" } %>
 <%= form.submit 'Search', data: { disable_with: false, action: "click->search#addQueryString" } %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= render partial: "partners/listing" %>
</table>

app/views/partners/new.html.erb
<h1>New partner</h1>

<%= render "form", partner: @partner %>

<br>

<div>
  <%= link_to "Back to partners", partners_path %>
</div>

app/views/partners/searches/index.html.erb
<h1>Partners::Searches#index</h1>
<p>Find me in app/views/partners/searches/index.html.erb</p>

app/views/partners/show.html.erb
<h1>Partner Managment</h1>

<%= turbo_frame_tag "partner" do %>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @partner.name %>
  </p>

  <%= link_to 'Edit', edit_partner_path(@partner) %> |
  <%= link_to 'Back', partners_path, data: { "turbo-frame": "_top" } %>
<% end %>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_list.html.erb
<div id="players">
  <div class="row">
    <% players.each do |player| %>
      <div class="card" style="width: 18rem;margin: 1rem;">
        <div class="card-body">
          <h5 class="card-title"><%= player.name %></h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link"><%= link_to 'Show', player %></a>
          <a href="#" class="card-link"><%= link_to 'Edit', edit_player_path(player) %></a>
          <a href="#" class="card-link"><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>
<%= form_with(url: search_players_path, data: { controller: 'form-submission', form_submission_target: "form" }) do |form| %>
  <%= form.label :query, "Search by name:" %>
  <%= form.text_field :query, data: { action: "input->form-submission#search" } %>
<% end %>

<%= render "list", players: @players %>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>